ScraperCatalogQueue:
  Type: AWS::SQS::Queue
  Properties:
    QueueName: catalog-queue
    VisibilityTimeout: 300

ScraperDetailQueue:
  Type: AWS::SQS::Queue
  Properties:
    QueueName: detail-queue
    VisibilityTimeout: 300

UploadProductDataQueue:
  Type: AWS::SQS::Queue
  Properties:
    QueueName: upload-product-data-queue
    VisibilityTimeout: 120