openapi: 3.1.0
info:
  title: Sneaker API
  version: 1.0.0
  description: Sneaker API

tags:
- name: Healthcheck
  description: Operations related to healthcheck
- name: Sneaker Management
  description: Operations related to sneaker management

paths:

    # healthcheck
    /healthcheck:
      get:
        $ref: ./openapi/healthcheck/get-healthcheck-status.yml

    # sneaker management 
    /sneakers:
      get:
        $ref: ./openapi/sneaker-management/list-all-sneaker-brands.yml
      post: 
        $ref: ./openapi/sneaker-management/create-sneaker.yml
    /sneakers/{brand}:
      get:
        $ref: ./openapi/sneaker-management/list-sneakers-by-brand.yml

    /sneakers/{brand}/{model}:    
      get:
        $ref: ./openapi/sneaker-management/get-sneaker.yml
      put: 
        $ref: ./openapi/sneaker-management/update-sneaker.yml
      post:
        $ref: ./openapi/sneaker-management/delete-sneaker.yml
