openapi: 3.1.0
info:
  title: Sneaker API
  version: 1.0.0
  description: Sneaker API

tags:
- name: Status
  description: Operations related to project version and documentation
- name: REST
  description: Operations related to scraped clothes database management
- name: Web Scraping
  description: Operations related to web scraping
- name: Scan
  description: Operations related to scanning an image

paths:

    # status
    /healthcheck:
      get:
        $ref: ./openapi/status/get-status.yml

    /docs:
      get: 
        $ref: ./openapi/status/get-docs.yml
      post: 
        $ref: ./openapi/status/post-docs.yml
    

    # rest 
    /api:
      get:
        $ref: ./openapi/rest/list-brands.yml
      post: 
        $ref: ./openapi/rest/create.yml
    /api/{brand}:
      get:
        $ref: ./openapi/rest/list-models.yml

    /api/{brand}/{model}:    
      get:
        $ref: ./openapi/rest/get.yml
      put: 
        $ref: ./openapi/rest/update.yml
      delete:
        $ref: ./openapi/rest/delete.yml

    # web scraping
    /scrape/{brand}:
      post: 
        $ref: ./openapi/scraper/start-scraping.yml

    # scan
    /scan:
      post: 
        $ref: ./openapi/scan/start-scan.yml
      get:
        $ref: ./openapi/scan/get-scans-by-user.yml
    /scan/{dataId}:
      get:
        $ref: ./openapi/scan/get-scan-result.yml
