service: sneaker-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  profile: sneaker-app
  region: us-west-2
  logRetentionInDays: 14
  timeout: 30
  apiGateway:
    binaryMediaTypes:
      - 'multipart/form-data'
  environment:
    DYNAMODB_SNEAKERS_TABLE: 'sneakers'
    S3_SNEAKERS_BUCKET: 'sneaker-api-sneakers-bucket'
    S3_DOCS_BUCKET: 'sneaker-api-docs-bucket'
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
        - s3:*
        - lambda:*
      Resource: "*"

plugins:
  - serverless-offline

functions:
  healthcheck: ${file(./serverless/healthcheck-function.yml):healthcheck}

  getDocs: ${file(./serverless/functions/documentation.yml):getDocs}

  createSneaker: ${file(./serverless/sneakers-function.yml):createSneaker}
  listSneakerBrands: ${file(./serverless/sneakers-function.yml):listSneakerBrands}
  listSneakersByBrand: ${file(./serverless/sneakers-function.yml):listSneakersByBrand}
  getOneSneaker: ${file(./serverless/sneakers-function.yml):getOneSneaker}
  updateOneSneaker: ${file(./serverless/sneakers-function.yml):updateOneSneaker}
  deleteOneSneaker: ${file(./serverless/sneakers-function.yml):deleteOneSneaker}

  # startScrapingProcess: ${file(./serverless/webscraper-function.yml):startScrapingProcess}
  # scrapeNikeDashboard: ${file(./serverless/webscraper-function.yml):scrapeNikeDashboard}
  # scrapeNikeBatch: ${file(./serverless/webscraper-function.yml):scrapeNikeBatch}
  # scrapeNotImplemented: ${file(./serverless/webscraper-function.yml):scrapeNotImplemented}

resources:
  Resources:
    DocsBucket: ${file(./serverless/resources/docs-bucket.yml):DocsBucket}
    SneakersTable: ${file(./serverless/resources/sneakers-table.yml):SneakersTable}
    SneakersBucket: ${file(./serverless/resources/sneakers-bucket.yml):SneakersBucket}
    IamApiRole: ${file(./serverless/resources/api-iamrole.yml):IamApiRole}
  #   WebScraperStateMachine: ${file(./serverless/webscraper-statemachine.yml):WebScraperStateMachine}
