service: sneaker-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  profile: sneaker-app
  region: us-west-2
  logRetentionInDays: 14

functions:
  healthcheck:
    handler: src/lambda/healthcheck/index.handler
    events:
      - httpApi:
          path: /healthcheck
          method: get

  sneakers:
    handler: src/lambda/sneakers/index.handler
    events:
      - httpApi:
          path: /sneakers
          method: get
      - httpApi:
          path: /sneakers
          method: post
      - httpApi:
          path: /sneakers/{sneakerId}
          method: get
      - httpApi:
          path: /sneakers/{sneakerId}
          method: put
      - httpApi:
          path: /sneakers/{sneakerId}
          method: delete