service: sneaker-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  profile: sneaker-app
  region: us-west-2
  logRetentionInDays: 14
  timeout: 30
  apiGateway:
    binaryMediaTypes:
      - 'multipart/form-data'
  environment:
    DYNAMODB_SNEAKERS_TABLE: 'sneakers'
    S3_SNEAKERS_BUCKET: 'sneaker-api-sneakers-bucket'
    S3_DOCS_BUCKET: 'sneaker-api-docs-bucket'
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
        - s3:*
        - lambda:*
      Resource: "*"

plugins:
  - serverless-offline

functions:
  healthcheck: ${file(./serverless/functions/healthcheck.yml):healthcheck}

  getDocs: ${file(./serverless/functions/documentation.yml):getDocs}

  createSneaker: ${file(./serverless/functions/sneakers.yml):createSneaker}
  listSneakerBrands: ${file(./serverless/functions/sneakers.yml):listSneakerBrands}
  listSneakersByBrand: ${file(./serverless/functions/sneakers.yml):listSneakersByBrand}
  getOneSneaker: ${file(./serverless/functions/sneakers.yml):getOneSneaker}
  updateOneSneaker: ${file(./serverless/functions/sneakers.yml):updateOneSneaker}
  deleteOneSneaker: ${file(./serverless/functions/sneakers.yml):deleteOneSneaker}

  startScrapingProcess: ${file(./serverless/functions/scrapers.yml):startScrapingProcess}
  scrapeUrl: ${file(./serverless/functions/scrapers.yml):scrapeUrl}
  scrapeIndividual: ${file(./serverless/functions/scrapers.yml):scrapeIndividual}

resources:
  Resources:
    DocsBucket: ${file(./serverless/resources/docs-bucket.yml):DocsBucket}
    SneakersTable: ${file(./serverless/resources/sneakers-table.yml):SneakersTable}
    SneakersBucket: ${file(./serverless/resources/sneakers-bucket.yml):SneakersBucket}
