service: sneaker-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  profile: sneaker-app
  region: us-west-2
  logRetentionInDays: 14

plugins:
  - serverless-offline

functions:
  healthcheck: ${file(./serverless/healthcheck-function.yml):healthcheck}
  sneakers: ${file(./serverless/sneakers-function.yml):sneakers}

resources:
  Resources:
    SneakersTable: ${file(./serverless/sneakers-table.yml):SneakersTable}
