service: sneaker-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  profile: sneaker-app
  region: us-west-2

functions:
  healthcheck:
    handler: src/lambda/healthcheck/index.handler
    events:
      - http:
          path: healthcheck
          method: get
          cors: true
