openapi: 3.0.3
info:
  title: Healthcheck API
  version: 1.0.0
  description: Healtcheck Endpoints

paths:
  /healthcheck:
    get:
      summary: Get Healthcheck Status
      responses:
        '200':
          description: OK
        '400':
          description: Bad request
        '404':
          description: Not found
        '500':
          description: Internal server error
      tags:
        - Healthcheck
