openapi: 3.0.3
info:
  title: Sneaker API
  version: 1.0.0
  description: Sneaker Endpoints

paths:
  /sneakers:
    get:
      summary: List all sneaker brands
      responses:
        '200':
          description: OK
        '400':
          description: Bad request
        '404':
          description: Not found
        '500':
          description: Internal server error
      tags:
        - Sneakers

    post:
      summary: Create a sneaker
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/createSneaker'
      responses:
        '200':
          description: OK
        '400':
          description: Bad request
        '404':
          description: Not found
        '500':
          description: Internal server error
      tags:
        - Sneakers

  /sneakers/{brand}:
    get:
      summary: List sneakers by brand
      parameters:
        - in: path
          name: brand
          required: true
          description: Sneaker brand
          schema:
            type: string
      responses:
        '200':
          description: OK
        '400':
          description: Bad request
        '404':
          description: Not found
        '500':
          description: Internal server error
      tags:
        - Sneakers

  /sneakers/{brand}/{model}:
    get:
      summary: Get details of a sneaker
      parameters:
        - in: path
          name: brand
          required: true
          description: Sneaker brand
          schema:
            type: string
        - in: path
          name: model
          required: true
          description: Sneaker model
          schema:
            type: string
      responses:
        '200':
          description: OK
        '400':
          description: Bad request
        '404':
          description: Not found
        '500':
          description: Internal server error
      tags:
        - Sneakers

    put:
      summary: Update details of a sneaker
      parameters:
        - in: path
          name: brand
          required: true
          description: Sneaker brand
          schema:
            type: string
        - in: path
          name: model
          required: true
          description: Sneaker model
          schema:
            type: string
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/updateSneaker'
      responses:
        '200':
          description: OK
        '400':
          description: Bad request
        '404':
          description: Not found
        '500':
          description: Internal server error
      tags:
        - Sneakers

    delete:
      summary: Delete a sneaker
      parameters:
        - in: path
          name: brand
          required: true
          description: Sneaker brand
          schema:
            type: string
        - in: path
          name: model
          required: true
          description: Sneaker model
          schema:
            type: string
      responses:
        '200':
          description: OK
        '400':
          description: Bad request
        '404':
          description: Not found
        '500':
          description: Internal server error
      tags:
        - Sneakers

components:
  schemas:
    createSneaker:
      type: object
      properties:
        brand:
          type: string
        model:
          type: string
        price:
          type: number
        pic1:
          type: string
          format: binary
        pic2:
          type: string
          format: binary
        pic3:
          type: string
          format: binary
        pic4:
          type: string
          format: binary
    updateSneaker:
      type: object
      properties:
        price:
          type: number
        pic1:
          type: string
          format: binary
        pic2:
          type: string
          format: binary
        pic3:
          type: string
          format: binary
        pic4:
          type: string
          format: binary