openapi: 3.0.3
info:
  title: Sneakers
  version: 1.0.0
  description: Sneakers Operations

paths:
  /sneakers:
    get:
      description: Get a list of sneakers
      responses:
        '200':
      tags:
        - Sneakers

    post:
      description: Create a new sneaker
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                brand:
                  type: string
                  description: Brand of the item
                model:
                  type: string
                  description: Model of the item
                price:
                  type: number
                  description: Price of the item
      responses:
        '201':
          description: Item created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int64
                    description: ID of the created item
                  brand:
                    type: string
                    description: Brand of the created item
                  model:
                    type: string
                    description: Model of the created item
                  price:
                    type: number
                    description: Price of the created item
        '400':
          description: Bad request
        '500':
          description: Internal server error
      tags:
        - Sneakers

  /sneakers/{brand}:
    get:
      description: Get sneakers by brand
      parameters:
        - name: brand
          in: path
          description: Brand of the sneakers to retrieve
          schema:
            type: string
      responses:
        '200':
          description: OK
        '404':
          description: Sneaker not found
        '500':
          description: Internal server error
      tags:
        - Sneakers

  /sneakers/{brand}/{model}:
    get:
      description: Get sneakers by brand and model
      parameters:
        - in: path
          name: brand
          description: Brand of the sneakers to retrieve
          schema:
            type: string
        - in: path
          name: model
          description: Model of the sneakers to retrieve
          schema:
            type: string
      responses:
        '200':
          description: OK
        '404':
          description: Sneaker not found
        '500':
          description: Internal server error
      tags:
        - Sneakers

    put:
      description: Update sneakers by brand and model
      parameters:
        - in: path
          name: brand
          description: Brand of the sneakers to update
          schema:
            type: string
        - in: path
          name: model
          description: Model of the sneakers to update
          schema:
            type: string
      responses:
        '200':
          description: Sneaker updated successfully
        '400':
          description: Bad request
        '404':
          description: Sneaker not found
        '500':
          description: Internal server error
      tags:
        - Sneakers

    delete:
      description: Delete sneakers by brand and model
      parameters:
        - in: path
          name: brand
          description: Brand of the sneakers to delete
          schema:
            type: string
        - in: path
          name: model
          description: Model of the sneakers to delete
          schema:
            type: string
      responses:
        '204':
          description: Sneaker deleted successfully
        '404':
          description: Sneaker not found
        '500':
          description: Internal server error
      tags:
        - Sneakers

tags:
  - name: Sneakers
    description: Operations related to sneakers
