dev: 
  DEPLOYMENT_NAME: ${self:service}
  ENVIRONMENT: ${self:provider.stage}
  
  APP_S3_ASSETS_BUCKET: 'clothes-detection-assets-bucket'

  APP_SCAN_TABLE_GSI_NAME: 'userName-gsi'
  APP_S3_SCAN_BUCKET: 'clothes-detection-scan-bucket'
  APP_DYNAMODB_SCAN_TABLE: 'scan-table'
 
  APP_DYNAMODB_INTEGRATIONS_TABLE: 'scraper-integration-table'
  APP_INTEGRATIONS_TABLE_GSI_NAME: 'brand-gsi'

  APP_DYNAMODB_SHIRTS_TABLE: 'shirts-table'
  APP_S3_SHIRTS_BUCKET: 'clothes-detection-shirts-bucket'
  APP_DYNAMODB_TROUSERS_TABLE: 'trousers-table'
  APP_S3_TROUSERS_BUCKET: 'clothes-detection-trousers-bucket'
  APP_DYNAMODB_SHOES_TABLE: 'shoes-table'
  APP_S3_SHOES_BUCKET: 'clothes-detection-shoes-bucket'

  REDIS_CACHE_CLUSTER: 'redis-cache-cluster'

  SENDER_MAIL: 'stylespotterapp@gmail.com'
  RECEIVER_MAIL: 'razvantamsa295@gmail.com'

  SQS_PRODUCT_CATALOG_QUEUE_URL: 'https://sqs.us-west-2.amazonaws.com/367859350018/catalog-queue'
  SQS_PRODUCT_DETAIL_QUEUE_URL: 'https://sqs.us-west-2.amazonaws.com/367859350018/detail-queue'
  SQS_UPLOAD_PRODUCT_DATA_QUEUE_URL: 'https://sqs.us-west-2.amazonaws.com/367859350018/upload-product-data-queue'

  APP_MAX_PRODUCT_LIMIT: 400