dev: 
  APP_S3_ASSETS_BUCKET: 'clothes-detection-assets-bucket'

  APP_SCAN_TABLE_GSI_NAME: 'userName-gsi'
  APP_S3_SCAN_BUCKET: 'clothes-detection-scan-bucket'
  APP_DYNAMODB_SCAN_TABLE: 'scan-table'
 
  APP_DYNAMODB_INTEGRATIONS_TABLE: 'scraper-integration-table'
  APP_INTEGRATIONS_TABLE_GSI_NAME: 'brand-gsi'

  APP_DYNAMODB_SHIRTS_TABLE: 'shirts-table'
  APP_S3_SHIRTS_BUCKET: 'clothes-detection-shirts-bucket'
  APP_DYNAMODB_TROUSERS_TABLE: 'trousers-table'
  APP_S3_TROUSERS_BUCKET: 'clothes-detection-trousers-bucket'
  APP_DYNAMODB_SHOES_TABLE: 'shoes-table'
  APP_S3_SHOES_BUCKET: 'clothes-detection-shoes-bucket'

  REDIS_CACHE_CLUSTER: 'redis-cache-cluster'

  SENDER_MAIL: 'stylespotterapp@gmail.com'
  RECEIVER_MAIL: 'razvantamsa295@gmail.com' 


  APP_MAX_PRODUCT_LIMIT: 400