ScraperIntegrationTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: scraper-integration-table
    AttributeDefinitions:
      - AttributeName: website
        AttributeType: S
      - AttributeName: brand
        AttributeType: S
    KeySchema:
      - AttributeName: website
        KeyType: HASH
      - AttributeName: brand
        KeyType: RANGE
    ProvisionedThroughput:
      ReadCapacityUnits: 5
      WriteCapacityUnits: 5
