ApikeySecret:
  Type: AWS::SecretsManager::Secret
  Properties:
    Name: authorization
    Description: apikey for request authorization
    SecretString: '{"apikey": "-"}'
  Metadata:
    AWS::SecretsManager::RotationLambdaARN: arn:aws:lambda:us-west-2:367859350018:function:clothes-detection-api-resources-dev-apikeyRotation

ApikeyRotation:
  handler: src/utils/authorizer/apikeyRotation.handler
  timeout: 600
  events:
    - schedule: rate(1 day)