ScanTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: scan-table
    AttributeDefinitions:
      - AttributeName: dataId
        AttributeType: S
      - AttributeName: user
        AttributeType: S
    KeySchema:
      - AttributeName: dataId
        KeyType: HASH
      - AttributeName: user
        KeyType: RANGE
    ProvisionedThroughput:
      ReadCapacityUnits: 5
      WriteCapacityUnits: 5

    GlobalSecondaryIndexes:
      - IndexName: user-gsi
        KeySchema:
          - AttributeName: user
            KeyType: HASH
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
