TrousersTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: trousers-table
    AttributeDefinitions:
      - AttributeName: brand
        AttributeType: S
      - AttributeName: model
        AttributeType: S
    KeySchema:
      - AttributeName: brand
        KeyType: HASH
      - AttributeName: model
        KeyType: RANGE
    ProvisionedThroughput:
      ReadCapacityUnits: 5
      WriteCapacityUnits: 5