ResourcesLogGroup:
  Type: AWS::Logs::LogGroup
  Properties:
    LogGroupName: microservice/resources
    RetentionInDays: 30

ResourcesLogStream:
  Type: AWS::Logs::LogStream
  DependsOn: [ResourcesLogGroup]
  Properties:
    LogGroupName: microservice/resources
    LogStreamName: index

ResourcesErrorMetricFilter:
  Type: AWS::Logs::MetricFilter
  DependsOn: [ResourcesLogGroup, ResourcesLogStream]
  Properties:
    LogGroupName: microservice/resources
    FilterPattern: "ERROR"
    MetricTransformations:
      - MetricValue: "1"
        MetricNamespace: "ResourcesErrorNamespace"
        MetricName: "ErrorCount"

ResourcesSuccessMetricFilter:
  Type: AWS::Logs::MetricFilter
  DependsOn: [ResourcesLogGroup, ResourcesLogStream]
  Properties:
    LogGroupName: microservice/resources
    FilterPattern: "INFO"
    MetricTransformations:
      - MetricValue: "1"
        MetricNamespace: "ResourcesSuccessNamespace"
        MetricName: "SuccessCount"