ScanLogGroup:
  Type: AWS::Logs::LogGroup
  Properties:
    LogGroupName: microservice/scan
    RetentionInDays: 30

ScanLogStream:
  Type: AWS::Logs::LogStream
  DependsOn: [ScanLogGroup]
  Properties:
    LogGroupName: microservice/scan
    LogStreamName: index

ScanErrorMetricFilter:
  Type: AWS::Logs::MetricFilter
  DependsOn: [ScanLogGroup, ScanLogStream]
  Properties:
    LogGroupName: microservice/scan
    FilterPattern: "ERROR"
    MetricTransformations:
      - MetricValue: "1"
        MetricNamespace: "ScanErrorNamespace"
        MetricName: "ErrorCount"

ScanSuccessMetricFilter:
  Type: AWS::Logs::MetricFilter
  DependsOn: [ScanLogGroup, ScanLogStream]
  Properties:
    LogGroupName: microservice/scan
    FilterPattern: "INFO"
    MetricTransformations:
      - MetricValue: "1"
        MetricNamespace: "ScanSuccessNamespace"
        MetricName: "SuccessCount"