ScraperLogGroup:
  Type: AWS::Logs::LogGroup
  Properties:
    LogGroupName: microservice/scraper
    RetentionInDays: 30

ScraperLogStream:
  Type: AWS::Logs::LogStream
  DependsOn: [ScraperLogGroup]
  Properties:
    LogGroupName: microservice/scraper
    LogStreamName: index

ScraperErrorMetricFilter:
  Type: AWS::Logs::MetricFilter
  DependsOn: [ScraperLogGroup, ScraperLogStream]
  Properties:
    LogGroupName: microservice/scraper
    FilterPattern: "ERROR"
    MetricTransformations:
      - MetricValue: "1"
        MetricNamespace: "ScraperErrorNamespace"
        MetricName: "ErrorCount"

ScraperSuccessMetricFilter:
  Type: AWS::Logs::MetricFilter
  DependsOn: [ScraperLogGroup, ScraperLogStream]
  Properties:
    LogGroupName: microservice/scraper
    FilterPattern: "INFO"
    MetricTransformations:
      - MetricValue: "1"
        MetricNamespace: "ScraperSuccessNamespace"
        MetricName: "SuccessCount"